serviceName: Apply for an Advance Tariff Ruling (ATaR)
serviceHeaderName: Apply for an Advance Tariff Ruling (ATaR)
serviceDescription: |
  The Apply for an Advance Tariff Ruling (ATaR) service allows a trader to apply for a commodity code. It can also allow them to view the status of their application and download a certificate.
serviceDomain: www.tax.service.gov.uk
serviceUrl: /advance-tariff-application
contactFrontendServiceId: BindingTariffApplication    # A unique identifier for your service
complianceStatus: partial
accessibilityProblems:
   - on the first page of the service, the links in the table header change the order of the content. This is not described to users so it can make it difficult to understand the content.
   - after users with screen readers choose to remove supporting documents, they are sent back to the top of the page. This change in context makes it difficult for users with screen reader users to understand if they have removed a file successfully.
   - in some places, the link text is not descriptive. For example, the first page of the service has a table where it’s not clear that the header links reorder the content. This can make it difficult for all users to navigate through the service - especially those using screen readers.
   - in some places, the page titles are the same. This can make it difficult for users to figure out where they are in the service.
   - if a user inputs a contact telephone number in the wrong format, they are not given an error message. This could mean that users could accidentally miss digits or enter the wrong characters.
   - the focus colour on some pages does not have a strong enough colour contrast. This could make it difficult for some users to see where they are on the screen.

milestones:
  - description:  "On the first page of the service, the links in the table header change the order of the content. This is not described to users so it can make it difficult to understand the content. This fails WCAG 2.1: 2.4.3 Focus Order and 1.3.1 Info and Relationships."
    date: 2021-02-26
  - description:  "After users with screen readers choose to remove supporting documents, they are sent back to the top of the page. This change in context makes it difficult for users with screen reader users to understand if they have removed a file successfully. This fails WCAG 2.1: 2.4.3 Focus Order and 1.3.1 Info and Relationships."
    date: 2021-02-26
  - description: "In some places, the link text is not descriptive. For example, the first page of the service has a table where it’s not clear that the header links reorder the content. This can make it difficult for all users to navigate through the service - especially those using screen readers. This fails WCAG 2.1: 2.4.4 Link Purpose (In Context)."
    date: 2021-02-26
  - description: "In some places, the page titles are the same. This can make it difficult for users to figure out where they are in the service. This fails WCAG 2.1: Name, Role, Value. 2.4.2 Page Titled."
    date: 2021-02-26
  - description: "If a user inputs a contact telephone number in the wrong format, they are not given an error message. This could mean that users could accidentally miss digits or enter the wrong characters. This fails WCAG 2.1: 3.3.1 Error Identification."
    date: 2021-02-26
  - description: "The focus colour on some pages does not have a strong enough colour contrast. This could make it difficult for some users to see where they are on the screen. This fails WCAG 2.1: 1.4.11 Non-text Contrast."
    date: 2021-02-26

serviceLastTestedDate: 2020-12-18
statementVisibility: public
statementCreatedDate: 2020-12-23
statementLastUpdatedDate: 2020-12-23

